name: Trigger Bot Restart on Push

on:
  push:
    branches: [main]  # Adjust branches as needed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      -name: update bot
       run: |
        git pull origin main
        


      - name: HTTP Request Action
        uses: fjogeleit/http-request-action@v1.16.3
        
        with:
          url: 'https://panel.cybrancee.com/api/client/servers/5abe55cb/power'
          method: 'POST'
          customHeaders: '{"Accept": "application/json", "Content-Type": "application/json", "Authorization": "Bearer ptlc_EBQWFHQ3AxArRWHVGv6u8afjp2oRVj7ootrbhsEnc8s"}'
          data: '{"signal": "restart"}'
