name: Trigger Bot Restart on Push

on:
  push:
    branches: [main]  # Adjust branches as needed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Check secret is set  
        run: |
          if [ -z "${{ secrets.PTERODACTYL_API_KEY }}" ]; then
          echo "❌ Secret is NOT set"
          else
            echo "✅ Secret is set"
          fi
        env:
          SECRE: ${{secrets.PTERODACTYL_API_KEY}}

              
      - name: HTTP Request Action
        uses: fjogeleit/http-request-action@v1.16.3
        
        with:
          url: 'https://panel.cybrancee.com/api/client/servers/5abe55cb/power'
          method: 'POST'
          customHeaders: '{"Accept": "application/json", "Content-Type": "application/json", "Authorization": "Bearer ${{ secrets.PTERODACTYL_API_KEY }}"}'
          data: '{"signal": "restart"}'
