name: Trigger Bot Restart on Push

on:
  push:
    branches: [main]  # Adjust branches as needed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Check secret is set  
        run: |
          if [ -z "${{ secrets.PTERODACTYL_API_KEY }}" ]; then
          echo "❌ Secret is NOT set"
          else
            echo "✅ Secret is set"
          fi
        env:
          SECRET: ${{secrets.PTERODACTYL_API_KEY}}

        
